INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT) VALUES ('Food', now(), false, now());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT) VALUES ('Clothes', now(), false, now());

INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('Cake', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('Fruit', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('Vegetables', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('Shoe', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Clothes');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('Hat', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Clothes');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('T-shirt', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Clothes');
INSERT INTO TB_CATEGORY (NAME, CREATED_AT, DELETED, UPDATED_AT, PARENT_ID) VALUES ('POLO', now(), false, now(), SELECT ID FROM TB_CATEGORY WHERE NAME = 'Clothes');

INSERT INTO TB_INVENTORY (NAME, CATEGORY_ID, SUB_CATEGORY_ID, QUANTITY, VERSION, CREATED_AT, DELETED, UPDATED_AT) VALUES ('Apple', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Fruit', 5, 0, now(), false, now());
INSERT INTO TB_INVENTORY (NAME, CATEGORY_ID, SUB_CATEGORY_ID, QUANTITY, VERSION, CREATED_AT, DELETED, UPDATED_AT) VALUES ('Pair', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Fruit', 10, 0, now(), false, now());
INSERT INTO TB_INVENTORY (NAME, CATEGORY_ID, SUB_CATEGORY_ID, QUANTITY, VERSION, CREATED_AT, DELETED, UPDATED_AT) VALUES ('Orange', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Food', SELECT ID FROM TB_CATEGORY WHERE NAME = 'Fruit', 8, 0, now(), false, now());